sky:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      host: localhost
      port: 3306
      database: sky_take_out
      username: root
      password: Tw!13560
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      host: localhost
      port: 3307
      database: sky_take_out
      username: root
      password: mysql3307
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxf2f0cbda4cc4fcc3
    secret: 536352a0ce60a3d7ebe322c7c09a7336
  shop:
    address: 广州市广东财经大学
  baidu:
    ak: DNow7WpSu1QGQ4IO1Ed7PsIjwlCyo7bt